<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Library\NicepayLib;

class RequestClickPay extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $nicepay = new NicepayLib();

        function generateReference()
        {
            $micro_date = microtime();
            $date_array = explode(" ",$micro_date);
            $date = date("YmdHis",$date_array[1]);
            $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
            return "Ref".$date.$date_array[0].rand(100,999);
        }
        $payMethod = $request->input('payMethod');
        $referenceNo = $request->input('referenceNo');
        if(isset($_POST['payMethod']) && $_POST['payMethod'] == '04'){

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '04');
            $nicepay->set('currency', 'IDR');
        
            if(!isset($_POST['referenceNo']) || $_POST['referenceNo'] == null){
                $nicepay->set('referenceNo', generateReference()); // Invoice Number or Reference Number Generated by merchant
            }else{
                $nicepay->set('referenceNo', $_POST['referenceNo']);
            }
        
            $nicepay->set('amt', $_POST['amt']); // Total gross amount
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description
        
            $nicepay->set('billingNm', 'John Doe'); // Customer name
            $nicepay->set('billingPhone', $_POST['billingPhone']); // Customer phone number
            $nicepay->set('billingEmail', 'john@example.com'); // Customer Email
            $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('billingCity', 'Jakarta Pusat');
            $nicepay->set('billingState', 'DKI Jakarta');
            $nicepay->set('billingPostCd', '10210');
            $nicepay->set('billingCountry', 'Indonesia');
        
            $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
            $nicepay->set('deliveryPhone', '082111111111');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');

            if ($_POST['mitraCd'] == 'JENC') {
                $nicepay->set('cartData', '{"count":"2","item":[{"img_url":"http://img.aaa.com/ima1.jpg","goods_name":"Item 1 Name","goods_detail":"Item 1 Detail","goods_amt":"7500","goods_quantity":"1"},{"img_url":"http://img.aaa.com/ima2.jpg","goods_name":"Item 2 Name","goods_detail":"Item 2 Detail","goods_amt":"7500","goods_quantity":"1"}]}');
            } else {
                $nicepay->set('cartData', '{"count":"2","item":[{"img_url":"http://img.aaa.com/ima1.jpg","goods_name":"Item 1 Name","goods_detail":"Item 1 Detail","goods_amt":"5000","goods_quantity":"1"},{"img_url":"http://img.aaa.com/ima2.jpg","goods_name":"Item 2 Name","goods_detail":"Item 2 Detail","goods_amt":"5000","goods_quantity":"1"}]}');
            }
        
            $timeStampRegist = date('Ymd').date('His');
            $nicepay->set('timeStamp', $timeStampRegist);
            $nicepay->set('reqDt', date('Ymd'));
            $nicepay->set('reqTm', date('His'));
            $nicepay->set('mitraCd', $_POST['mitraCd']); // ClickPay
            // Send Data
            $response = $nicepay->requestClickPay();

            // Response from NICEPAY
            if (isset($response->resultCd) && $response->resultCd == "0000") {
                $timeStampPayment = date('Ymd').date('His');
                $nicepay->set('timeStamp', $timeStampPayment);
                $nicepay->set('iMid', NICEPAY_IMID);
                $nicepay->set('referenceNo', $response->referenceNo);
                $nicepay->set('amt', $response->amt);
                $nicepay->set('merchantKey', NICEPAY_MERCHANT_KEY);
                $merchantToken = $nicepay->merchantToken();
                $callBackUrl = NICEPAY_CALLBACK_URL;

                return redirect()->route('paymentClickPay', 'tXid='.$response->tXid.'&timeStamp='.$timeStampPayment.'&referenceNo='.$response->referenceNo.'&amt='.$response->amt.'&callBackUrl='.$callBackUrl.'&merchantToken='.$merchantToken);

            } elseif (isset($response->resultCd)) {
                return redirect()->route('otherError', (array) $response);
            } else {
                $request->session()->flash('msg', 'Connection Timeout. Please Try Again!');
            }

            
        }
    }
}