<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Library\NicepayLib;

class RequestPayloan extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $nicepay = new NicepayLib();

        function generateReference()
        {
            $micro_date = microtime();
            $date_array = explode(" ",$micro_date);
            $date = date("YmdHis",$date_array[1]);
            $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
            return "Ref".$date.$date_array[0].rand(100,999);
        }
        
        if(isset($_POST['payMethod']) && $_POST['payMethod'] == '06'){

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '06');
            $nicepay->set('currency', 'IDR');

            if(!isset($_POST['referenceNo']) || $_POST['referenceNo'] == null){
                $nicepay->set('referenceNo', generateReference()); // Invoice Number or Reference Number Generated by merchant
            }else{
                $nicepay->set('referenceNo', $_POST['referenceNo']);
            }

            if ( $_POST['mitraCd'] == 'KDVI') {
                $cartData = '{"count":"1","item":[{"goods_id":"A1213","goods_detail":"BB12345678","goods_name":"Nokia","goods_amt":"12000","goods_type":"Sembako","goods_url":"http://merchant.com/cellphones/iphone5s_64g","goods_quantity":"1","goods_sellers_id":"NICEPAY-NamaMerchant","goods_sellers_name":"NICEPAYSHOP"}]}';
            } elseif ($_POST['mitraCd'] == 'AKLP') {
                $cartData = '{"count":"1","item":[{"goods_id":"A1213","goods_detail":"BB12345678","goods_name":"Nokia","goods_amt":"12000","goods_type":"services","goods_url":"http://merchant.com/cellphones/iphone5s_64g","goods_quantity":"1","goods_sellers_id":"NICEPAY-NamaMerchant","goods_sellers_name":"NICEPAYSHOP"}]}';
            } elseif ($_POST['mitraCd'] == 'IDNA') {
                $cartData = '{"count":"1","item":[{"goods_id":"A1213","goods_detail":"BB12345678","goods_name":"Nokia","goods_amt":"12000","goods_type":"services","goods_url":"http://merchant.com/cellphones/iphone5s_64g","goods_quantity":"1","goods_sellers_id":"NICEPAY-NamaMerchant","goods_sellers_name":"NICEPAYSHOP"}]}';
            }

            if ( $_POST['mitraCd'] == 'KDVI') {
                $sellers = '[{"sellersId":"NICEPAY-NamaMerchant","sellersNm":"NICEPAYSHOP","sellersEmail":"sellers@test.com","sellersAddress":{"sellerNm":"NICEPAYSHOP","sellerLastNm":"NICEPAYSHOP","sellerAddr":"jalan berbangsa 1","sellerCity":"Jakarta Barat","sellerPostCd":"12345","sellerPhone":"082111111111","sellerCountry":"ID"}}]';
            } elseif ($_POST['mitraCd'] == 'AKLP') {
                $sellers = '[{"sellersId":"NICEPAY-NamaMerchant","sellersNm":"NICEPAYSHOP","sellersEmail":"sellers@test.com","sellersAddress":{"sellerNm":"NICEPAYSHOP","sellerLastNm":"NICEPAYSHOP","sellerAddr":"jalan berbangsa 1","sellerCity":"Jakarta Barat","sellerPostCd":"12345","sellerPhone":"082111111111","sellerCountry":"ID"}}]';
            } elseif ($_POST['mitraCd'] == 'IDNA') {
                $sellers = '[{"sellersId":"NICEPAY-NamaMerchant","sellersNm":"NICEPAYSHOP","sellersUrl":"http://nicestore.store/product/beanie/","sellersEmail":"sellers@test.com","sellersAddress":{"sellerNm":"NICEPAYSHOP","sellerLastNm":"NICEPAYSHOP","sellerAddr":"jalan berbangsa 1","sellerCity":"Jakarta Barat","sellerPostCd":"12345","sellerPhone":"082111111111","sellerCountry":"ID"}}]';
            }

            $nicepay->set('amt', $_POST['amt']); // Total gross amount
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description

            $nicepay->set('goodsNm', 'Test Transaction');
            $nicepay->set('billingNm', 'John Doe'); // Customer name
            $nicepay->set('billingPhone', '082111111111');
            $nicepay->set('billingEmail', 'john@example.com'); // Customer Email
            $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('billingCity', 'Jakarta Pusat');
            $nicepay->set('billingState', 'DKI Jakarta');
            $nicepay->set('billingPostCd', '10210');
            $nicepay->set('billingCountry', 'Indonesia');

            $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
            $nicepay->set('deliveryPhone', '02112345678');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');

            $nicepay->set('instmntType', '2');
            $nicepay->set('instmntMon', $_POST['instmntMon']);
            $nicepay->set('recurrOpt', '1');
            $nicepay->set('payValidDt', '');
            $nicepay->set('payValidTm', '');
            $nicepay->set('deliveryCountry', 'Indonesia');
            $nicepay->set('mitraCd', $_POST['mitraCd']);

            $timeStampRegist = date('Ymd').date('His');
            $nicepay->set('timeStamp', $timeStampRegist);
            $nicepay->set('reqDt', date('Ymd'));
            $nicepay->set('reqTm', date('His'));
            $nicepay->set('reqDomain', 'merchant.com');
            $nicepay->set('userIP', '127.0.0.1');
            $nicepay->set('reqServerIP', '127.0.0.1');
            $nicepay->set('reqClientVer', '');
            $nicepay->set('userSessionID', '697D6922C961070967D3BA1BA5699C2C');
            $nicepay->set('userAgent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/60.0.3112.101 Safari/537.36');
            $nicepay->set('userLanguage', 'ko-KR,en-US;q=0.8,ko;q=0.6,en;q=0.4');
            $nicepay->set('vacctValidDt', '');
            $nicepay->set('vacctValidTm', '');
            $nicepay->set('merFixAcctId', '');
            $nicepay->set('cartData', $cartData);
            $nicepay->set('sellers', $sellers);
            $nicepay->set('bankCd', '');
        
            $nicepay->set('mitraCd', $_POST['mitraCd']);
            
            // Send Data
            $response = $nicepay->requestPayloan();

            // Response from NICEPAY
            if(isset($response->resultCd) && $response->resultCd == "0000") {
                $timeStampPayment = date('Ymd').date('His');
                $nicepay->set('timeStamp', $timeStampPayment);
                $nicepay->set('iMid', NICEPAY_IMID);
                $nicepay->set('referenceNo', $response->referenceNo);
                $nicepay->set('amt', $response->amt);
                $nicepay->set('merchantKey', NICEPAY_MERCHANT_KEY);
                $merchantToken = $nicepay->merchantToken();
                $callBackUrl = NICEPAY_CALLBACK_URL;

                redirect()->to(NICEPAY_ORDER_PAYMENT_URL."?tXid=".$response->tXid."&timeStamp=".$timeStampPayment."&callBackUrl=".$callBackUrl."&merchantToken=".$merchantToken)->send();
                
            } elseif(isset($response->resultCd)) {
                return redirect()->route('otherError', (array) $response);
            } else{
                $request->session()->flash('msg', 'Connection Timeout. Please Try Again!');
            }
        }
    }
}
