<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Library\NicepayLib;

class RequestPayout extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $nicepay = new NicepayLib();
        function generateReference()
        {
            $micro_date = microtime();
            $date_array = explode(" ", $micro_date);
            $date = date("YmdHis", $date_array[1]);
            $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
            return "Ref" . $date . $date_array[0] . rand(100, 999);
        }

        if(isset($_POST['payMethod']) && $_POST['payMethod'] == '07'){

            // Populate Mandatory parameters to send
            $nicepay->set('accountNo', $_POST['accountNo']);
            $nicepay->set('benefNm', 'John Wayne');
        
            if(!isset($_POST['referenceNo']) || $_POST['referenceNo'] == null){
                $nicepay->set('referenceNo', generateReference()); // Invoice Number or Reference Number Generated by merchant
            }else{
                $nicepay->set('referenceNo', $_POST['referenceNo']);
            }
        
            $nicepay->set('amt', $_POST['amt']); // Total gross amount
            $nicepay->set('benefStatus', '1');
        
            $nicepay->set('benefType', '1');  
            $nicepay->set('reservedDt', ''); // Schedule Date Example 20220324
            $nicepay->set('reservedTm', ''); // Schedule Time Example 120000
            $nicepay->set('benefPhone', $_POST['benefPhone']);
            // $nicepay->set('benefPOE', 'Kota Administrasi Jakarta Selatan');
            // $nicepay->set('benefDOE', '220101');
            // $nicepay->set('benefCoNo', '12345JP');
            // $nicepay->set('benefAddr', 'Jl. Hong Gil Dong 88');
        
            // $nicepay->set('deliveryNm', 'Paul'); // Delivery name
            // $nicepay->set('deliveryId', '1234567890234512');
            // $nicepay->set('benefAuthPhoneNumber', '081623516151725378');
            // $nicepay->set('benefMerCategory', '01');
            // $nicepay->set('benefCoMgmtNm', 'John Wayne');
            // $nicepay->set('benefCoShNm', 'John Wayne');
        
            $timeStamp = date('Ymd').date('His');
            $nicepay->set('timeStamp', $timeStamp);
        
            $nicepay->set('bankCd', 'BDIN');
            $nicepay->set('description', 'Test Payout');

            // print_r($nicepay);exit();
        
            // Send Data
            $response = $nicepay->requestPayout();

            // print_r($response);exit();

            // Response from NICEPAY
            if (isset($response->resultCd) && $response->resultCd == "0000") {

                return redirect()->route('resultPayout', 'tXid='.
                    $response->tXid.'&referenceNo='.$response->referenceNo.
                    '&resultMsg='.$response->resultMsg.
                    '&amt='.$response->amt.
                    '&accountNo='.$response->accountNo.
                    '&bankCd='.$response->bankCd.
                    '&benefNm='.$response->benefNm
                );

            } 
            elseif(isset($response->resultCd)) {
                return redirect()->route('otherError', (array) $response);
            } else {
                $request->session()->flash('msg', 'Connection Timeout. Please Try Again!');
            }
        }
    }
}
