<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Library\NicepayLib;

class RequestEWallet extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $nicepay = new NicepayLib();

        function generateReference()
        {
            $micro_date = microtime();
            $date_array = explode(" ",$micro_date);
            $date = date("YmdHis",$date_array[1]);
            $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
            return "Ref".$date.$date_array[0].rand(100,999);
        }
        $payMethod = $request->input('payMethod');
        $referenceNo = $request->input('referenceNo');
        if(isset($_POST['payMethod']) && $_POST['payMethod'] == '05'){

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '05');
            $nicepay->set('currency', 'IDR');
        
            if(!isset($_POST['referenceNo']) || $_POST['referenceNo'] == null){
                $nicepay->set('referenceNo', generateReference()); // Invoice Number or Reference Number Generated by merchant
            }else{
                $nicepay->set('referenceNo', $_POST['referenceNo']);
            }
        
            $nicepay->set('amt', $_POST['amt']); // Total gross amount
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description
        
            $nicepay->set('billingNm', 'John Doe'); // Customer name
            $nicepay->set('billingPhone', $_POST['phoneNumber']); // Customer phone number
            $nicepay->set('billingEmail', 'john@example.com'); // Customer Email
            $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('billingCity', 'Jakarta Pusat');
            $nicepay->set('billingState', 'DKI Jakarta');
            $nicepay->set('billingPostCd', '10210');
            $nicepay->set('billingCountry', 'Indonesia');
        
            $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
            $nicepay->set('deliveryPhone', '02112345678');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');
        
            $timeStampRegist = date('Ymd').date('His');
            $nicepay->set('timeStamp', $timeStampRegist);
            $nicepay->set('reqDt', date('Ymd'));
            $nicepay->set('reqTm', date('His'));
        
            $nicepay->set('mitraCd', $_POST['mitraCd']); // Ewallet
            // Send Data
            $response = $nicepay->requestEWallet();

            function isMobile() {
            return preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"]);
        }

            if(isset($response->resultCd) && $response->resultCd == "0000") {
                if(!isMobile() && $response->mitraCd == "ESHP"){
                    $message = "E-Wallet Shopeepay only support mobile devices. to continue payment, please open this page with mobile browser";
                    echo "<script type='text/javascript'>alert('$message');</script>";
                    echo "<script>window.location=history.go(-1);</script>";
                } else {
                    $timeStampPayment = date('Ymd').date('His');
                    $nicepay->set('timeStamp', $timeStampPayment);
                    $nicepay->set('iMid', NICEPAY_IMID);
                    $nicepay->set('referenceNo', $response->referenceNo);
                    $nicepay->set('amt', $response->amt);
                    $nicepay->set('merchantKey', NICEPAY_MERCHANT_KEY);
                    $merchantToken = $nicepay->merchantToken();
                    //$callBackUrl = NICEPAY_CALLBACK_URL;
                }
                //print_r($response);exit();

                if($response->mitraCd == 'DANA' || $response->mitraCd == 'LINK' || $response->mitraCd == 'OVOE'){
                    $callBackUrl = NICEPAY_CALLBACK_URL;
                } else {
                    $callBackUrl = ('http://de71-103-78-209-131.ngrok.io/result');
                }
                redirect()->to("https://www.nicepay.co.id/nicepay/direct/v2/payment"."?tXid=".$response->tXid."&timeStamp=".$timeStampPayment."&callBackUrl=".$callBackUrl."&merchantToken=".$merchantToken)->send();
                
            } else{
                $request->session()->flash('msg', 'Connection Timeout. Please Try Again!');
            }
        }
    }
}